version: '3.8'
services:
  # bot:
  #   image: dndscribe  # Use pre-built image instead of building
  #   volumes:
  #     - ./bot.py:/app/bot.py
  #     - ./ignored.txt:/app/ignored.txt
  #     - ./.env:/app/.env
  #     - ./recordings:/app/recordings
  #     - ./models:/app/models
  #   depends_on:
  #     ollama:
  #       condition: service_healthy
  #   networks:
  #     - ollama-docker
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    # networks:
    #   - ollama-docker

networks:
  ollama-docker:
    external: false